### ISSUE TITLE
Open up the Google Group so anyone can see discussion without having to apply for membership

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#83]
The current plan is to open up the [new AOGPN Google Group](https://groups.google.com/forum/#!forum/aogpn) so anyone can see and join in the discussion.

It currently isn't open and requires people to apply, we need to remove that setting.

This will enable anyone to immediately start working on Action Plan commitments.

**Comment by kat** [comment]
Based on the wording in the welcome text of the email group which states that it's an open group intended for use by Network members.

"Welcome to this discussion group for the Australian Open Government Partnership Network (AOGPN).

The AOGPN is a network of individuals and organisations interested in supporting the Australian government's progress towards full and ongoing membership of the Open Government Partnership (opengovpartnership.org).

This discussion group has been established to support*\* a public discussion **of potential priorities for the National Action Plan currently being developed by the Australian Government (refer ogpau.govspace.gov.au).

The priorities discussed and detailed in this group will be submitted to the Australian government for potential inclusion in the first Australian OGP National Action Plan.

We support positive and constructive posting and will moderate posts which do not contribute to the design of potential priorities.

**Comment by craigthomler** [comment]
Done. Made it a public group.

Have left the first post of new users as moderated to manage spam.

I'll promote people to Manager (to manage their discussions) as they register to the group.

**Comment by equivalentideas** [comment]
Nice one :+1:

**Comment by henare** [comment]
Nice, it looks like you can now easily join. However you still can't view any of the group's content:

![selection_001](https://cloud.githubusercontent.com/assets/48945/12739484/43c50d66-c9be-11e5-9ae8-a307cd01cfcd.png)

I think you need to set _View topics_ to _Public_ under the Group's _Basic Settings_:

![selection_002](https://cloud.githubusercontent.com/assets/48945/12739527/89d9415a-c9be-11e5-96c1-25340c5f7e22.png)

**Comment by craigthomler** [comment]
OK - taken that step. I've left posting as members only.

I also promoted Kat to Owner and the other Steering Committee members to Managers.

Henare & Luke, want to be Owners too?

**Comment by equivalentideas** [comment]
Nice one @craigthomler it's all open now :star2: :star: :star2: :star: :star2: :star: :star2: :star: I'll close this.

> Henare & Luke, want to be Owners too?

May as well add us to thanks, incase something comes up to change quickly.

**Comment by craigthomler** [comment]
You need to register as a member first :)

I haven't pushed invites out to either of you as I wasn't sure which email
addresses you prefer to use.

Cheers,

Craig

---

Craig Thomler

http://egovau.blogspot.com
http://twitter.com/CraigThomler
http://au.linkedin.com/in/craigthomler
http://www.slideshare.net/CraigThomler
http://www.slideshare.net/CraigThomler%20

_Mobile:_ 0411 780 194 (_International:_ +61 411 780 194)
_Phone:_ 02 6161 4508 (_International: *+61 2 6161 4508)
*Skype:_ craig.thomler

**Comment by henare** [comment]
Great, thanks @craigthomler  :+1: I've now registered as a member as henare@oaf.org.au

**Comment by craigthomler** [comment]
Have elevated you to Owner Henare. Which means you could elevate Luke if he joins.

**Comment by henare** [comment]
Cheers @craigthomler :sparkles:
